// 函数: sub_4b65f0
// 地址: 0x4b65f0
// 来自: E:\torrent\AliceSoft\ランス01\Rance01.exe

long double x87_r7_3 = fconvert.t(*arg2) * fconvert.t(*arg3)
    + fconvert.t(arg2[1]) * fconvert.t(arg3[4]) + fconvert.t(arg3[8]) * fconvert.t(arg2[2])
    + fconvert.t(arg3[0xc]) * fconvert.t(arg2[3])
*arg4 = fconvert.s(x87_r7_3)
arg4[1] = fconvert.s(fconvert.t(arg3[5]) * fconvert.t(arg2[1])
    + fconvert.t(*arg2) * fconvert.t(arg3[1]) + fconvert.t(arg3[9]) * fconvert.t(arg2[2])
    + fconvert.t(arg2[3]) * fconvert.t(arg3[0xd]))
arg4[2] = fconvert.s(fconvert.t(arg3[6]) * fconvert.t(arg2[1])
    + fconvert.t(arg3[2]) * fconvert.t(*arg2) + fconvert.t(arg2[2]) * fconvert.t(arg3[0xa])
    + fconvert.t(arg2[3]) * fconvert.t(arg3[0xe]))
arg4[3] = fconvert.s(fconvert.t(arg3[7]) * fconvert.t(arg2[1])
    + fconvert.t(*arg2) * fconvert.t(arg3[3]) + fconvert.t(arg3[0xb]) * fconvert.t(arg2[2])
    + fconvert.t(arg2[3]) * fconvert.t(arg3[0xf]))
arg4[4] = fconvert.s(fconvert.t(arg2[4]) * fconvert.t(*arg3)
    + fconvert.t(arg2[5]) * fconvert.t(arg3[4]) + fconvert.t(arg3[8]) * fconvert.t(arg2[6])
    + fconvert.t(arg3[0xc]) * fconvert.t(arg2[7]))
arg4[5] = fconvert.s(fconvert.t(arg2[4]) * fconvert.t(arg3[1])
    + fconvert.t(arg3[5]) * fconvert.t(arg2[5]) + fconvert.t(arg3[9]) * fconvert.t(arg2[6])
    + fconvert.t(arg2[7]) * fconvert.t(arg3[0xd]))
arg4[6] = fconvert.s(fconvert.t(arg2[5]) * fconvert.t(arg3[6])
    + fconvert.t(arg2[4]) * fconvert.t(arg3[2]) + fconvert.t(arg2[6]) * fconvert.t(arg3[0xa])
    + fconvert.t(arg3[0xe]) * fconvert.t(arg2[7]))
arg4[7] = fconvert.s(fconvert.t(arg2[4]) * fconvert.t(arg3[3])
    + fconvert.t(arg3[7]) * fconvert.t(arg2[5]) + fconvert.t(arg3[0xb]) * fconvert.t(arg2[6])
    + fconvert.t(arg2[7]) * fconvert.t(arg3[0xf]))
arg4[8] = fconvert.s(fconvert.t(arg2[8]) * fconvert.t(*arg3)
    + fconvert.t(arg2[9]) * fconvert.t(arg3[4]) + fconvert.t(arg3[8]) * fconvert.t(arg2[0xa])
    + fconvert.t(arg3[0xc]) * fconvert.t(arg2[0xb]))
arg4[9] = fconvert.s(fconvert.t(arg2[8]) * fconvert.t(arg3[1])
    + fconvert.t(arg3[5]) * fconvert.t(arg2[9]) + fconvert.t(arg3[9]) * fconvert.t(arg2[0xa])
    + fconvert.t(arg2[0xb]) * fconvert.t(arg3[0xd]))
arg4[0xa] = fconvert.s(fconvert.t(arg2[9]) * fconvert.t(arg3[6])
    + fconvert.t(arg2[8]) * fconvert.t(arg3[2]) + fconvert.t(arg2[0xa]) * fconvert.t(arg3[0xa])
    + fconvert.t(arg2[0xb]) * fconvert.t(arg3[0xe]))
arg4[0xb] = fconvert.s(fconvert.t(arg2[8]) * fconvert.t(arg3[3])
    + fconvert.t(arg3[7]) * fconvert.t(arg2[9]) + fconvert.t(arg3[0xb]) * fconvert.t(arg2[0xa])
    + fconvert.t(arg2[0xb]) * fconvert.t(arg3[0xf]))
arg4[0xc] = fconvert.s(fconvert.t(arg2[0xc]) * fconvert.t(*arg3)
    + fconvert.t(arg2[0xd]) * fconvert.t(arg3[4]) + fconvert.t(arg3[8]) * fconvert.t(arg2[0xe])
    + fconvert.t(arg3[0xc]) * fconvert.t(arg2[0xf]))
arg4[0xd] = fconvert.s(fconvert.t(arg2[0xc]) * fconvert.t(arg3[1])
    + fconvert.t(arg3[5]) * fconvert.t(arg2[0xd]) + fconvert.t(arg3[9]) * fconvert.t(arg2[0xe])
    + fconvert.t(arg2[0xf]) * fconvert.t(arg3[0xd]))
arg4[0xe] = fconvert.s(fconvert.t(arg2[0xd]) * fconvert.t(arg3[6])
    + fconvert.t(arg2[0xc]) * fconvert.t(arg3[2]) + fconvert.t(arg2[0xe]) * fconvert.t(arg3[0xa])
    + fconvert.t(arg2[0xf]) * fconvert.t(arg3[0xe]))
arg4[0xf] = fconvert.s(fconvert.t(arg2[0xc]) * fconvert.t(arg3[3])
    + fconvert.t(arg3[7]) * fconvert.t(arg2[0xd]) + fconvert.t(arg3[0xb]) * fconvert.t(arg2[0xe])
    + fconvert.t(arg2[0xf]) * fconvert.t(arg3[0xf]))
return arg4
